set pagesize 200 linesize 200 heading on feedback on verify off echo off
col owner format a30
col username format a30
col table_count format 999999
col object_count format 999999
col account_status format a20

prompt === NON-SYSTEM USERS ===

select username,
       account_status
  from dba_users
 where username not in (
   'ANONYMOUS','APEX_030200','APEX_040000','APEX_040200','APEX_PUBLIC_USER',
   'APPQOSSYS','AUDSYS','CSMIG','CTXSYS','DBSFWUSER','DBSNMP','DBMS_PRIVILEGE_CAPTURE',
   'DIP','DVF','DVSYS','EXFSYS','FLOWS_FILES','GSMADMIN_INTERNAL','LBACSYS',
   'MDDATA','MDSYS','MGDSYS','MGMT_VIEW','ODM','ODM_MTR','OJVMSYS','OLAPSYS',
   'ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OSE$HTTP$ADMIN','OUTLN',
   'PERFSTAT','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR',
   'SQLTXPLAIN','SYS','SYSTEM','SYSMAN','SDE','TSMSYS','TRACESRV','WKPROXY',
   'WKSYS','WK_TEST','WMSYS','XDB','XS$NULL'
 )
 order by username;

prompt === TABLE COUNTS ===

select owner,
       count(*) as table_count
  from dba_tables
 where owner not in (
   'ANONYMOUS','APEX_030200','APEX_040000','APEX_040200','APEX_PUBLIC_USER',
   'APPQOSSYS','AUDSYS','CSMIG','CTXSYS','DBSFWUSER','DBSNMP','DBMS_PRIVILEGE_CAPTURE',
   'DIP','DVF','DVSYS','EXFSYS','FLOWS_FILES','GSMADMIN_INTERNAL','LBACSYS',
   'MDDATA','MDSYS','MGDSYS','MGMT_VIEW','ODM','ODM_MTR','OJVMSYS','OLAPSYS',
   'ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OSE$HTTP$ADMIN','OUTLN',
   'PERFSTAT','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR',
   'SQLTXPLAIN','SYS','SYSTEM','SYSMAN','SDE','TSMSYS','TRACESRV','WKPROXY',
   'WKSYS','WK_TEST','WMSYS','XDB','XS$NULL'
 )
 group by owner
 order by count(*) desc, owner;

prompt === OBJECT COUNTS ===

select owner,
       count(*) as object_count
  from dba_objects
 where owner not in (
   'ANONYMOUS','APEX_030200','APEX_040000','APEX_040200','APEX_PUBLIC_USER',
   'APPQOSSYS','AUDSYS','CSMIG','CTXSYS','DBSFWUSER','DBSNMP','DBMS_PRIVILEGE_CAPTURE',
   'DIP','DVF','DVSYS','EXFSYS','FLOWS_FILES','GSMADMIN_INTERNAL','LBACSYS',
   'MDDATA','MDSYS','MGDSYS','MGMT_VIEW','ODM','ODM_MTR','OJVMSYS','OLAPSYS',
   'ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OSE$HTTP$ADMIN','OUTLN',
   'PERFSTAT','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR',
   'SQLTXPLAIN','SYS','SYSTEM','SYSMAN','SDE','TSMSYS','TRACESRV','WKPROXY',
   'WKSYS','WK_TEST','WMSYS','XDB','XS$NULL'
 )
 group by owner
 order by count(*) desc, owner;

exit
