-- =============================================================
-- 01_create_dms_users.sql
-- AWS DMS / DMS Schema Conversion 용 Oracle 접속 계정·권한 생성.
-- 대상: ORCL (CDB, 멀티테넌트) → 공통 사용자(C##) 로 생성, CONTAINER=ALL.
-- 실행: sqlplus / as sysdba @migration/aws-dms/01_create_dms_users.sql
-- 멱등: 기존 계정 DROP 후 재생성.
--
-- 계정:
--   C##DMS_SC  : DMS Schema Conversion(메타데이터 읽기 전용)
--   C##DMS     : DMS 데이터 마이그레이션 소스(Full Load + CDC 준비)
--
-- 비고:
--   - Full Load + Schema Conversion 은 NOARCHIVELOG 에서도 동작.
--   - CDC(LogMiner)는 ARCHIVELOG + 보충로깅 필요(02_enable_cdc.sql, 재시작 동반).
--
-- 비밀번호는 파일에 저장하지 않는다. 실행 시 인자(위치변수)로 전달:
--   sqlplus / as sysdba @01_create_dms_users.sql <C##DMS_SC_PW> <C##DMS_PW>
-- 권장 규칙: 비밀번호 = 아이디(대문자) 역순. 예) 운영자가 생성:
--   SC_PW=$(printf '%s' 'C##DMS_SC' | rev);  SRC_PW=$(printf '%s' 'C##DMS' | rev)
-- 인자 미전달 시 SQL*Plus 가 대화식으로 입력을 요구한다(역시 파일 미저장).
-- =============================================================
SET SQLBLANKLINES ON
SET DEFINE ON
SET VERIFY OFF
ALTER SESSION SET CONTAINER = CDB$ROOT;

-- 기존 계정 정리
DECLARE
  PROCEDURE drop_user(p VARCHAR2) IS
  BEGIN EXECUTE IMMEDIATE 'DROP USER '||p||' CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN
  drop_user('C##DMS_SC');
  drop_user('C##DMS');
END;
/

-- ============================================================
-- 1) Schema Conversion 계정 (읽기 전용 메타데이터)
-- ============================================================
CREATE USER C##DMS_SC IDENTIFIED BY "&1" CONTAINER=ALL;
ALTER USER C##DMS_SC DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS CONTAINER=ALL;
GRANT CONNECT                TO C##DMS_SC CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE    TO C##DMS_SC CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY  TO C##DMS_SC CONTAINER=ALL;
GRANT SELECT ON SYS.ARGUMENT$ TO C##DMS_SC CONTAINER=ALL;

-- ============================================================
-- 2) DMS 소스 계정 (Full Load + CDC 준비)
-- ============================================================
CREATE USER C##DMS IDENTIFIED BY "&2" CONTAINER=ALL;
ALTER USER C##DMS DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS CONTAINER=ALL;

GRANT CREATE SESSION         TO C##DMS CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO C##DMS CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY  TO C##DMS CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE    TO C##DMS CONTAINER=ALL;
-- Full Load 시 소스 테이블 데이터 읽기(테스트 편의: 전체 테이블).
-- 최소권한이 필요하면 아래 한 줄 대신 'GRANT SELECT ON <schema>.<table> ...' 로 대체.
GRANT SELECT ANY TABLE       TO C##DMS CONTAINER=ALL;

-- V$ 동적 성능 뷰
GRANT SELECT ON V_$ARCHIVED_LOG    TO C##DMS CONTAINER=ALL;
GRANT SELECT ON V_$LOG             TO C##DMS CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE         TO C##DMS CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS     TO C##DMS CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO C##DMS CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE        TO C##DMS CONTAINER=ALL;
GRANT SELECT ON V_$THREAD          TO C##DMS CONTAINER=ALL;
GRANT SELECT ON V_$PARAMETER       TO C##DMS CONTAINER=ALL;
GRANT SELECT ON V_$NLS_PARAMETERS  TO C##DMS CONTAINER=ALL;
GRANT SELECT ON V_$TIMEZONE_NAMES  TO C##DMS CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION     TO C##DMS CONTAINER=ALL;
GRANT SELECT ON V_$CONTAINERS      TO C##DMS CONTAINER=ALL;

-- 데이터 사전(메타데이터)
GRANT SELECT ON ALL_INDEXES            TO C##DMS CONTAINER=ALL;
GRANT SELECT ON ALL_OBJECTS            TO C##DMS CONTAINER=ALL;
GRANT SELECT ON ALL_TABLES             TO C##DMS CONTAINER=ALL;
GRANT SELECT ON ALL_USERS              TO C##DMS CONTAINER=ALL;
GRANT SELECT ON ALL_CATALOG            TO C##DMS CONTAINER=ALL;
GRANT SELECT ON ALL_CONSTRAINTS        TO C##DMS CONTAINER=ALL;
GRANT SELECT ON ALL_CONS_COLUMNS       TO C##DMS CONTAINER=ALL;
GRANT SELECT ON ALL_TAB_COLS           TO C##DMS CONTAINER=ALL;
GRANT SELECT ON ALL_IND_COLUMNS        TO C##DMS CONTAINER=ALL;
GRANT SELECT ON ALL_ENCRYPTED_COLUMNS  TO C##DMS CONTAINER=ALL;
GRANT SELECT ON ALL_LOG_GROUPS         TO C##DMS CONTAINER=ALL;
GRANT SELECT ON ALL_TAB_PARTITIONS     TO C##DMS CONTAINER=ALL;
GRANT SELECT ON SYS.DBA_REGISTRY       TO C##DMS CONTAINER=ALL;
GRANT SELECT ON SYS.OBJ$               TO C##DMS CONTAINER=ALL;
GRANT SELECT ON DBA_TABLESPACES        TO C##DMS CONTAINER=ALL;
GRANT SELECT ON SYS.ARGUMENT$          TO C##DMS CONTAINER=ALL;

-- 데이터 검증(선택)
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO C##DMS CONTAINER=ALL;

-- LogMiner / CDC (권한만 미리 부여; 실제 CDC 는 ARCHIVELOG 필요)
GRANT EXECUTE ON DBMS_LOGMNR TO C##DMS CONTAINER=ALL;
GRANT LOGMINING              TO C##DMS CONTAINER=ALL;

-- Binary Reader 사용 시(선택, 광범위 권한이라 기본 비활성):
-- GRANT SELECT ON SYS.DBA_DIRECTORIES TO C##DMS CONTAINER=ALL;
-- GRANT CREATE ANY DIRECTORY TO C##DMS CONTAINER=ALL;

PROMPT >> 01_create_dms_users.sql 완료: C##DMS_SC / C##DMS 생성 및 권한 부여
